import jsPDF from 'jspdf';
import PptxGenJS from 'pptxgenjs';
import { downloadFile } from '../utils/helpers';

/**
 * Export analysis as PDF
 */
export function exportAsPDF(analysis) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper to add text with page breaks
  const addText = (text, fontSize = 12, style = 'normal', color = [0, 0, 0], indent = 0) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    
    const lines = doc.splitTextToSize(text, maxWidth - indent);
    lines.forEach(line => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin + indent, yPosition);
      yPosition += fontSize * 0.5; // Line height
    });
    yPosition += 2; // Paragraph spacing
  };

  // Helper for section headers
  const addSectionHeader = (title) => {
    yPosition += 5;
    if (yPosition > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
    
    // Draw background for header
    doc.setFillColor(240, 249, 255); // Light blue
    doc.rect(margin - 2, yPosition - 6, maxWidth + 4, 10, 'F');
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 165, 233); // Prism Blue
    doc.text(title.toUpperCase(), margin, yPosition);
    yPosition += 10;
  };

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59); // Slate 800
  const titleLines = doc.splitTextToSize(analysis.title, maxWidth);
  doc.text(titleLines, margin, yPosition);
  yPosition += titleLines.length * 12 + 5;

  // Metadata
  doc.setDrawColor(203, 213, 225); // Slate 300
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  if (analysis.authors && analysis.authors.length > 0) {
    addText(`Authors: ${analysis.authors.join(', ')}`, 10, 'italic', [100, 116, 139]);
  }
  if (analysis.publicationYear) {
    addText(`Year: ${analysis.publicationYear}`, 10, 'italic', [100, 116, 139]);
  }
  yPosition += 10;

  // Executive Summary
  addSectionHeader('Executive Summary');
  addText(analysis.summary, 11, 'normal', [51, 65, 85]);
  yPosition += 5;

  // Key Takeaways
  addSectionHeader('Key Takeaways');
  analysis.takeaways.forEach((takeaway, i) => {
    addText(`${i + 1}. ${takeaway}`, 11, 'normal', [51, 65, 85]);
  });
  yPosition += 5;

  // Methodology
  addSectionHeader('Methodology');
  addText(analysis.methodology, 11, 'normal', [51, 65, 85]);
  yPosition += 5;

  // Key Findings
  addSectionHeader('Key Findings & Evidence');
  analysis.keyFindings.forEach((finding, i) => {
    addText(`Finding ${i + 1}: ${finding.finding}`, 11, 'bold', [30, 41, 59]);
    addText(`"${finding.evidence}"`, 10, 'italic', [71, 85, 105], 5);
    yPosition += 4;
  });

  // Critique Section (if available)
  if (analysis.strengths || analysis.weaknesses) {
    addSectionHeader('Critical Analysis');
    
    if (analysis.strengths) {
      addText('Strengths:', 12, 'bold', [22, 163, 74]); // Green
      analysis.strengths.forEach((s, i) => addText(`• ${s.point}`, 11, 'normal', [51, 65, 85], 5));
      yPosition += 5;
    }
    
    if (analysis.weaknesses) {
      addText('Limitations:', 12, 'bold', [220, 38, 38]); // Red
      analysis.weaknesses.forEach((w, i) => addText(`• ${w.point}`, 11, 'normal', [51, 65, 85], 5));
    }
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by Prism Research Assistant | Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  // Save
  doc.save(`${analysis.title.substring(0, 30).replace(/[^a-z0-9]/gi, '_')}_Analysis.pdf`);
}

/**
 * Export analysis as Markdown
 */
export function exportAsMarkdown(analysis) {
  const date = new Date().toLocaleDateString();
  let markdown = `# ${analysis.title}\n\n`;
  
  markdown += `> **Generated by Prism Research Assistant** on ${date}\n\n`;

  if (analysis.authors && analysis.authors.length > 0) {
    markdown += `**👥 Authors:** ${analysis.authors.join(', ')}\n\n`;
  }
  if (analysis.publicationYear) {
    markdown += `**📅 Year:** ${analysis.publicationYear}\n\n`;
  }

  markdown += `---\n\n`;

  markdown += `## 🚀 Executive Summary\n\n${analysis.summary}\n\n`;

  markdown += `## 🔑 Key Takeaways\n\n`;
  analysis.takeaways.forEach((takeaway, i) => {
    markdown += `- ${takeaway}\n`;
  });
  markdown += `\n`;

  markdown += `## 🔬 Methodology\n\n${analysis.methodology}\n\n`;

  markdown += `## 💡 Key Findings & Evidence\n\n`;
  analysis.keyFindings.forEach((finding, i) => {
    markdown += `### ${i + 1}. ${finding.finding}\n`;
    markdown += `> *"${finding.evidence}"*\n\n`;
  });

  if (analysis.strengths || analysis.weaknesses) {
    markdown += `## ⚖️ Critical Analysis\n\n`;
    
    if (analysis.strengths) {
      markdown += `### ✅ Strengths\n`;
      analysis.strengths.forEach((s) => markdown += `- ${s.point}\n`);
      markdown += `\n`;
    }

    if (analysis.weaknesses) {
      markdown += `### ⚠️ Limitations\n`;
      analysis.weaknesses.forEach((w) => markdown += `- ${w.point}\n`);
      markdown += `\n`;
    }
  }

  if (analysis.hypotheses) {
    markdown += `## 🧪 Future Research Hypotheses\n\n`;
    analysis.hypotheses.forEach((hyp, i) => {
      markdown += `### Hypothesis ${i + 1}\n`;
      markdown += `**Hypothesis:** ${hyp.hypothesis}\n\n`;
      markdown += `**Experimental Design:** ${hyp.experimentalDesign}\n\n`;
      if (hyp.expectedOutcome) {
        markdown += `**Expected Outcome:** ${hyp.expectedOutcome}\n\n`;
      }
      markdown += `---\n`;
    });
  }

  markdown += `\n---\n*Analysis generated by Prism AI*`;

  downloadFile(markdown, `${analysis.title.substring(0, 30).replace(/[^a-z0-9]/gi, '_')}_Analysis.md`, 'text/markdown');
}

/**
 * Export presentation as PPTX
 */
export function exportAsPPTX(presentation, paperTitle) {
  const pptx = new PptxGenJS();

  // Set presentation properties
  pptx.author = 'Prism AI';
  pptx.title = paperTitle || 'Research Analysis';
  pptx.subject = 'Research Paper Analysis';

  // Define theme colors
  const colors = {
    primary: '0ea5e9',
    secondary: '8b5cf6',
    accent: 'ec4899',
    text: '1e293b',
    lightBg: 'f8fafc'
  };

  // Create slides
  presentation.slides.forEach((slideData, index) => {
    const slide = pptx.addSlide();

    // Add gradient background
    if (index === 0) {
      // Title slide
      slide.background = { fill: colors.primary };
      
      slide.addText(slideData.title, {
        x: 0.5,
        y: 2.0,
        w: '90%',
        h: 1.5,
        fontSize: 44,
        bold: true,
        color: 'FFFFFF',
        align: 'center',
        valign: 'middle'
      });

      slide.addText('Generated by Prism AI', {
        x: 0.5,
        y: 4.5,
        w: '90%',
        fontSize: 18,
        color: 'FFFFFF',
        align: 'center',
        italic: true
      });
    } else {
      // Content slides
      slide.background = { fill: 'FFFFFF' };

      // Title
      slide.addText(slideData.title, {
        x: 0.5,
        y: 0.5,
        w: '90%',
        h: 0.8,
        fontSize: 32,
        bold: true,
        color: colors.primary,
        align: 'left'
      });

      // Decorative line
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.5,
        y: 1.4,
        w: 9.0,
        h: 0.05,
        fill: { color: colors.secondary }
      });

      // Content bullets
      const bulletText = slideData.content.map(item => ({ text: item, options: { bullet: true, fontSize: 18, color: colors.text } }));
      
      slide.addText(bulletText, {
        x: 0.7,
        y: 1.8,
        w: 8.6,
        h: 3.5,
        fontSize: 18,
        color: colors.text,
        bullet: { type: 'number' },
        lineSpacing: 30
      });

      // Footer
      slide.addText(`Slide ${index}`, {
        x: 8.5,
        y: 5.2,
        w: 1.0,
        fontSize: 12,
        color: '94a3b8',
        align: 'right'
      });
    }
  });

  // Save presentation
  const fileName = paperTitle ? `${paperTitle.substring(0, 50)}_presentation.pptx` : 'research_presentation.pptx';
  pptx.writeFile({ fileName });
}

/**
 * Export multi-paper synthesis
 */
export function exportSynthesisAsPDF(synthesis, paperTitles) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  const addText = (text, fontSize = 12, style = 'normal', color = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach(line => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
    yPosition += 5;
  };

  // Title
  addText('MULTI-PAPER SYNTHESIS', 18, 'bold', [14, 165, 233]);
  yPosition += 10;

  // Papers analyzed
  addText('PAPERS ANALYZED', 14, 'bold', [139, 92, 246]);
  paperTitles.forEach((title, i) => {
    addText(`${i + 1}. ${title}`, 10);
  });
  yPosition += 10;

  // Overall synthesis
  addText('OVERALL SYNTHESIS', 14, 'bold', [139, 92, 246]);
  addText(synthesis.overallSynthesis, 11);
  yPosition += 10;

  // Common themes
  addText('COMMON THEMES', 14, 'bold', [139, 92, 246]);
  synthesis.commonThemes.forEach((theme, i) => {
    addText(`Theme ${i + 1}: ${theme.theme}`, 11, 'bold');
    addText(`Discussed in: ${theme.papersDiscussing.join(', ')}`, 10, 'italic');
    yPosition += 5;
  });
  yPosition += 10;

  // Conflicting findings
  addText('CONFLICTING FINDINGS', 14, 'bold', [139, 92, 246]);
  synthesis.conflictingFindings.forEach((conflict, i) => {
    addText(`${i + 1}. ${conflict.topic}`, 11, 'bold');
    addText(conflict.conflicts, 10);
    yPosition += 5;
  });
  yPosition += 10;

  // Concept evolution
  addText('CONCEPT EVOLUTION', 14, 'bold', [139, 92, 246]);
  addText(synthesis.conceptEvolution, 11);

  doc.save('multi_paper_synthesis.pdf');
}
